version: '3'
services:
  server:
    build:
      context: ./json-rpc-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
