version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/rpc/Dockerfile
    ports:
      - ":8080"
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lamoda
    ports:
      - 5432:5432
